import { ThemeDefinition } from '../types';

export const builtInThemes: ThemeDefinition[] = [
  {
    id: 'midnight-blueprint',
    name: 'Midnight Blueprint',
    description: 'A precise dark theme built from the original app direction, but normalized into tokens.',
    mode: 'dark',
    builtIn: true,
    tokens: {
      appBg: '#0b1016',
      sidebarBg: '#0f151d',
      panelBg: '#151d27',
      panelAltBg: '#101721',
      elevatedBg: '#1a2430',
      borderColor: '#253343',
      textPrimary: '#edf3fb',
      textSecondary: '#b5c0d1',
      textMuted: '#73839b',
      accent: '#79b8ff',
      accentSoft: '#162a45',
      accentContrast: '#f8fbff',
      success: '#7ee2bf',
      successSoft: '#15372d',
      danger: '#ff8f96',
      dangerSoft: '#482126',
      focus: '#8ec6ff',
      overlay: 'rgba(3, 7, 12, 0.8)',
    },
  },
  {
    id: 'graphite-terminal',
    name: 'Graphite Terminal',
    description: 'High-contrast monochrome with acid-green interaction states.',
    mode: 'dark',
    builtIn: true,
    tokens: {
      appBg: '#0b0d0f',
      sidebarBg: '#111417',
      panelBg: '#171b1f',
      panelAltBg: '#0f1215',
      elevatedBg: '#1d2328',
      borderColor: '#2a3239',
      textPrimary: '#eff5ec',
      textSecondary: '#c5d0c2',
      textMuted: '#7f8b81',
      accent: '#8dfc7a',
      accentSoft: '#1f3b1f',
      accentContrast: '#071107',
      success: '#9df7ad',
      successSoft: '#1b3520',
      danger: '#ff8d80',
      dangerSoft: '#48211d',
      focus: '#b0ff93',
      overlay: 'rgba(0, 0, 0, 0.8)',
    },
  },
  {
    id: 'paper-ledger',
    name: 'Paper Ledger',
    description: 'A bright editorial light theme for planning and review sessions.',
    mode: 'light',
    builtIn: true,
    tokens: {
      appBg: '#ece4d6',
      sidebarBg: '#e0d5c2',
      panelBg: '#f7f1e7',
      panelAltBg: '#efe6d8',
      elevatedBg: '#fffaf0',
      borderColor: '#c7baa5',
      textPrimary: '#33291e',
      textSecondary: '#5d4c3e',
      textMuted: '#8f7c69',
      accent: '#8f4b24',
      accentSoft: '#e5cfbf',
      accentContrast: '#fff8f2',
      success: '#2f7d55',
      successSoft: '#d9efe2',
      danger: '#b84d4d',
      dangerSoft: '#f3d9d9',
      focus: '#b56b40',
      overlay: 'rgba(39, 26, 12, 0.18)',
    },
  },
  {
    id: 'atelier-notebook',
    name: 'Atelier Notebook',
    description: 'Warm ivory paper, graphite ruling, and cognac accents for a refined notebook feel.',
    mode: 'light',
    builtIn: true,
    tokens: {
      appBg: '#ebe7df',
      sidebarBg: '#66707d',
      panelBg: '#fffef9',
      panelAltBg: '#f8f4eb',
      elevatedBg: '#ffffff',
      borderColor: '#ddd6ca',
      textPrimary: '#1f2937',
      textSecondary: '#4b5b70',
      textMuted: '#758295',
      accent: '#8d6e63',
      accentSoft: '#ebe2d8',
      accentContrast: '#fffdf9',
      success: '#496c63',
      successSoft: '#e2ece8',
      danger: '#b45a50',
      dangerSoft: '#f5e1dd',
      focus: '#8095be',
      overlay: 'rgba(31, 41, 55, 0.14)',
    },
  },
  {
    id: 'e-ink-digital-paper',
    name: 'E-Ink Digital Paper',
    description: 'A low-stimulation monochrome paper theme optimized for long reading and planning.',
    mode: 'light',
    builtIn: true,
    tokens: {
      appBg: '#efede6',
      sidebarBg: '#e3e0d8',
      panelBg: '#f6f4ee',
      panelAltBg: '#ece8df',
      elevatedBg: '#fbfaf6',
      borderColor: '#b7b1a5',
      textPrimary: '#1f1d19',
      textSecondary: '#49443b',
      textMuted: '#706a5d',
      accent: '#3b372f',
      accentSoft: '#d9d4c8',
      accentContrast: '#f8f6f0',
      success: '#394236',
      successSoft: '#dde3d8',
      danger: '#5a3a34',
      dangerSoft: '#e6d7d3',
      focus: '#5c5648',
      overlay: 'rgba(18, 16, 13, 0.26)',
    },
  },
  {
    id: 'cupertino-frosted-glass',
    name: 'Cupertino Frosted Glass',
    description: 'A polished desktop-inspired glass theme with restrained translucency and crisp hierarchy.',
    mode: 'light',
    builtIn: true,
    tokens: {
      appBg: '#e8edf4',
      sidebarBg: '#dce4ef',
      panelBg: '#f7fbff',
      panelAltBg: '#edf3fb',
      elevatedBg: '#ffffff',
      borderColor: '#c7d3e3',
      textPrimary: '#182331',
      textSecondary: '#3f5368',
      textMuted: '#6d7f92',
      accent: '#0a84ff',
      accentSoft: '#d8eaff',
      accentContrast: '#ffffff',
      success: '#1fa971',
      successSoft: '#d8f3e6',
      danger: '#d94848',
      dangerSoft: '#f8dede',
      focus: '#5aa9ff',
      overlay: 'rgba(12, 22, 38, 0.24)',
    },
  },
  {
    id: 'cyberpunk-synthwave',
    name: 'Cyberpunk Synthwave',
    description: 'A high-energy dark neon theme with restrained glow and productivity-first contrast.',
    mode: 'dark',
    builtIn: true,
    tokens: {
      appBg: '#070912',
      sidebarBg: '#0b1020',
      panelBg: '#11162a',
      panelAltBg: '#0b1020',
      elevatedBg: '#161d33',
      borderColor: '#273458',
      textPrimary: '#eef3ff',
      textSecondary: '#bcc7ea',
      textMuted: '#7f8db5',
      accent: '#ff38b8',
      accentSoft: '#3a1240',
      accentContrast: '#fff2fb',
      success: '#2cf7c4',
      successSoft: '#10373a',
      danger: '#ff6b8e',
      dangerSoft: '#4a1d2e',
      focus: '#32d3ff',
      overlay: 'rgba(2, 4, 10, 0.82)',
    },
  },
  {
    id: 'forest-dusk',
    name: 'Forest Dusk',
    description: 'A softer dark theme with moss greens and muted twilight contrast.',
    mode: 'dark',
    builtIn: true,
    tokens: {
      appBg: '#0f1714',
      sidebarBg: '#13201c',
      panelBg: '#182722',
      panelAltBg: '#101b17',
      elevatedBg: '#21322c',
      borderColor: '#2e453d',
      textPrimary: '#e3eee8',
      textSecondary: '#b4c6bc',
      textMuted: '#768c81',
      accent: '#7bc7a4',
      accentSoft: '#234233',
      accentContrast: '#08130d',
      success: '#95e1b8',
      successSoft: '#18382b',
      danger: '#f68f8f',
      dangerSoft: '#482626',
      focus: '#9bddbd',
      overlay: 'rgba(3, 10, 7, 0.78)',
    },
  },
];
