name = "too-much-to-do-api"
main = "src/index.ts"
compatibility_date = "2026-03-05"

[[d1_databases]]
binding = "DB"
database_name = "too-much-to-do"
database_id = "a255a273-95bd-4248-aee3-53fdd299fa0c"
migrations_dir = "migrations"

[vars]
APP_SCHEMA_LATEST = "4"
APP_SCHEMA_MIN_SUPPORTED = "4"
SESSION_COOKIE_NAME = "tmtd_session"
SESSION_COOKIE_SAME_SITE = "Lax"


[triggers]
crons = ["0 4 * * *"]
